WIP 9 - split code
imfaber/vue-tasty-burgers pull request #11
Opened 2019-12-30 20:54 UTC by pniedzwiedzinski

As I commented in #9 the CSS could be split. I've done it on a few components and I want to know, what you think about it.

I also added storybook since it's easier than creating temp vue app for testing.

2020-01-03 09:43 UTC, imfaber requested changes
Hi @pniedzwiedzinski 

Great job! I love your proposal.
My only concern is about having a tag per component. 
I'd rather have one tag where I can specify the hamburger type `<vue-tasty-burger type="slider">`.

This could be achieved with dynamic components.
Here a quick example.
```js
<template>
  <component v-bind:is="components[type]" v-on="$listeners"></component>
</template>

<script>
const components = {
  slider: () => import('./SliderHamburger.vue')
  // ... the other components
}

export default {
  components,
  props: {
    type: String
  },
  data() {
    return {
      components
    }
  }
}
</script>
```

Does it make sense?
Any thought?

Many thanks for your work.

2020-01-03 09:43 UTC, imfaber commented on src/components/BoringHamburger.vue
> +  <plain-hamburger class="hamburger--boring" @toggle="$emit('toggle')" />
I would automatically pass any event to the parent with `v-on="$listeners"`
```suggestion
  <plain-hamburger class="hamburger--boring" v-on="$listeners />
```

PS. the same for the other components

2020-01-03 09:43 UTC, imfaber commented on package.json
> +    "@storybook/vue": "^5.2.8",
❤️

2020-01-03 10:18 UTC, pniedzwiedzinski commented
I wasn't familiar with dynamic components, and this preserves more compatibility with previous versions, which is great.
Ok, I will keep working on that

2020-01-26 19:55 UTC, pniedzwiedzinski commented
I have problems with rollup and I couldn't make it work. Maybe you could check it and see what's wrong?

2020-03-02 07:53 UTC, imfaber commented
Sorry, I've been quite busy lately.. I'll have a look ASAP

2020-04-18 08:01 UTC, merged